package org.powbot.dax.api.models;

public enum WalkerPreferences {
	CHRONICLE,

	SPIRIT_TREE_BRIMHAVEN,
	SPIRIT_TREE_ETCTETERIA,
	SPIRIT_TREE_HOSIDIUS,
	SPIRIT_TREE_PORT_SARIM,
	SPIRIT_TREE_FARMING_GUILD,

	MYCELIUM_NODE_HOUSE_ON_THE_HILL,
	MYCELIUM_NODE_MUSHROOM_MEADOW,
	MYCELIUM_NODE_STICKY_SWAMP,
	MYCELIUM_NODE_VERDANT_VALLEY,

	ARDOUGNE_CLOAK_FARM,
	DESERT_AMULET_NARDAH,
	FREMENNIK_SEA_BOOTS_RELLEKKA,
	RADAS_BLESSING_KOUREND_WOODLAND,
	RADAS_BLESSING_MOUNT_KARUULM,


}
